config/routes.rb
Rails.application.routes.draw do
  resources :movies
  resources :tickets, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :tickets
end

app/models/ticket.rb
class Ticket < ApplicationRecord

  belongs_to :movie


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController


  def index
    @movies = Movie.all
    render :index
  end

  def new
    @movie = Movie.new
    render :new
  end

  def create
    @movie = Movie.create(movie_params)
    redirect_to movies_path
  end

  def show
    @movie = Movie.find(params[:id])
    @tickets = Ticket.all
    render :show
  end

  def edit
    @movie = Movie.find(params[:id])
    render :edit
  end

  def update
    @movie = Movie.find(params[:id])
    @movie.update(movie_params)
    redirect_to movie_path(@movie)
  end

  def destroy
    #code
  end

private
  def movie_params
    params.require(:movie).permit(:name, :year)
  end


end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController

  def new
    @ticket = Ticket.new
    render :new
  end

  def create
    @ticket = Ticket.create(ticket_params)
    @movie = Movie.find(ticket_params[:movie_id])
    redirect_to movie_path(@movie)
  end

  private
  def ticket_params
    params.require(:ticket).permit(:movie_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/seats_helper.rb
module SeatsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TicketMaster</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :year %>
  <%= f.number_field :year %>

  <%= f.submit %>

<% end %>

app/views/movies/edit.html.erb
<h1>Update your movie</h1>

<%= render partial: "form" %>

app/views/movies/index.html.erb
<h1>MOVIES</h1>

<% @movies.each do |movie| %><br>
<%= link_to movie.name, movie %> | <%= movie.year %><br>
<% end %>

app/views/movies/new.html.erb
<h1>Create new Movie!</h1>

<%= render partial: "form" %>

app/views/movies/show.html.erb
<h1><%= @movie.name %></h1>
<h2><%= @movie.year %></h2>

Seat has been taken: <% ticket_numbers = @tickets.select do |ticket| %>
                  <% ticket.movie_id == @movie.id %>
                  <% end %>
                  <% ticket_numbers.each do |t| %>
                    <%= t.id %>
                  <% end %><br>


<%= link_to "Edit", edit_movie_path(@movie) %>

<%= link_to "New Ticket", new_ticket_path %>

<%= link_to "All Movies", movies_path %>

app/views/tickets/new.html.erb
<h1>Create TICKET</h1>

<%= form_for @ticket do |f| %>

  <%= f.label "Movie_id" %>
  <%= f.number_field :movie_id %>

  <%= f.submit %>
<% end %>